### ISSUE TITLE
 ModuleBuildError: Module build failed: ReferenceError: Symbol is not defined

### ISSUE THREAD

**Issue by roblg** [ben-eb/colormin#2]
The ES6 change threw us for a loop this morning. We're using node 0.10.x in one part of our build (but only for a little while longer!), and we had builds start failing this morning. The reason appears to be the the upgrade of colormin to 1.0.3. Babel's output on `src/lib/toLonghand.js` uses `Symbol`, which isn't defined in node 0.10.x.

We get the following error:

```
ModuleBuildError: Module build failed: ReferenceError: Symbol is not defined
```

This isn't a huge deal for us, but I figured someone else might have the same problem, so the neighborly thing to do would be to report it.

We'll probably either shrinkwrap with the previous version, or push through a node upgrade. :)

**Comment by ben-eb** [comment]
This is weird because I test this module on `0.10`, and got this error in one build. The rest of the builds passed but on closer inspection they are still throwing the error but exit with code 0.

https://travis-ci.org/ben-eb/postcss-colormin/jobs/73928760

I'll push a patch out because I intended to support `0.10` with this module for a little while longer. Sorry about this.

**Comment by ben-eb** [comment]
Released as `1.0.4`. Can you please verify? :smile:

https://travis-ci.org/ben-eb/postcss-colormin/jobs/73929205

**Comment by roblg** [comment]
Looks good! Thanks for the quick turnaround!

**Comment by ben-eb** [comment]
No problem. :+1:

**Comment by powdahound** [comment]
Just ran into this as well and it was awesome to find the fix was already made and waiting in npm by the time I found this ticket. Thanks!

**Comment by ben-eb** [comment]
You're welcome. :smiley:
